# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MathProject_config = debug
endif
ifeq ($(config),release)
  MathProject_config = release
endif

PROJECTS := MathProject

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MathProject:
ifneq (,$(MathProject_config))
	@echo "==== Building MathProject ($(MathProject_config)) ===="
	@${MAKE} --no-print-directory -C . -f MathProject.make config=$(MathProject_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f MathProject.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MathProject"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"